# Site settings
title: Reading&Thinking
name: Reading&Thinking
email: mangj@foxmail.com
description: 'Noodles&#039;s Free Space'
keywords: 'Noodles,Noodles,blog,c,c++,python,unix-like'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.manguijie.top" # the base hostname & protocol for your site
github: noodlesmomo
twitter: 

author:
  name: NoodlesMoMo
  email: mangj@foxmail.com
  github: noodlesmomo
  twitter: 
  bio: 'Noodles&#039;s Blog'
  email_md5: 48704463cba11c09f03346a052a2f33e


# Build settings
paginate: 10
paginate_path: "page/:num/"
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
#pygments: true 
#markdown: redcarpet
markdown: kramdown
rss_path: feed
categories_path: categories.html
tags_path: tags.html
